import turtle


def guniv():
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(200)
    turtle.up()
    turtle.right(180)
    turtle.forward(100)
    turtle.left(90)
    turtle.down()
    turtle.fillcolor('black')
    turtle.begin_fill()
    for i in range(4):
        turtle.forward(25)
        turtle.right(90)
    turtle.end_fill()
    turtle.up()
    turtle.forward(175)
    turtle.down()
    turtle.fillcolor('black')
    turtle.begin_fill()
    for i in range(4):
        turtle.forward(25)
        turtle.right(90)
    turtle.end_fill()
    turtle.up()
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(25)
    turtle.down()
    turtle.fillcolor('black')
    turtle.begin_fill()
    for i in range(1):
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(25)
        turtle.left(90)
        turtle.forward(25)
        turtle.right(90)
        turtle.forward(25)
        turtle.left(90)
        turtle.forward(25)
        turtle.left(90)
        turtle.forward(25)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(25)
    turtle.end_fill()
    turtle.right(180)
    turtle.up()
    turtle.forward(25)
    turtle.down()
    turtle.fillcolor('red')
    turtle.begin_fill()
    for i in range(1):
        turtle.forward(25)
        turtle.right(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(25)
    turtle.end_fill()
    turtle.done()